// THIS FILE IS GENERATED BY TOOL, PLEASE DO NOT EDIT!

import Foundation

struct R {

    enum string : String {
        /// test jest ok
        case test
        /// integer %d, napis %@
        case test_parameters1
        /// napis %2$d, integer %1$@
        case test_parameters2
    }

    enum plurals : String {
        case test_plurals

        subscript(quantity: Int) -> String {
            return String.localizedStringWithFormat(NSLocalizedString(self.rawValue, comment: ""), quantity)
        }
    }

}

