# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hash',
            field=models.CharField(default='nicnic', max_length=10),
            preserve_default=False,
        ),
    ]
