# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
