# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171007_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hash',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['hash'], name='api_group_hash_75abd8_idx'),
        ),
    ]
