# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171007_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorRoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_room_id', models.CharField(max_length=100)),
                ('last_activity', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='data',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='last_owner_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
